package productreviewmining;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;

import productreviewmining.util.Tokenizers;
import productreviewmining.polarity.Polarity;
import productreviewmining.util.POS;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws IOException {

        String labrinthReview = String.join("\n", Files
                .readAllLines(Paths.get("./build/resources/main/samples/labrinth-review.txt")));

        List<String> sentences = Arrays.asList(Tokenizers.sentenceDetector.sentDetect(labrinthReview));
        List<String> subjectiveSentences = sentences
                .stream()
                .filter((s) -> Polarity.calculateSentencePolarity(s) >= 0)
                .collect(Collectors.toList());

        for(String sent: subjectiveSentences) {
            String[] tokenized = Tokenizers.tokenizer.tokenize(sent);
            String[] tags = POS.tagger.tag(tokenized);
            System.out.println(Arrays.asList(tokenized));
            System.out.println(Arrays.asList(tags));
        }
    }
}
